### ISSUE TITLE
[1.6.5.0] Fraud system is not up to date

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#10]
In OC2.x, the fraud system has moved from the store settings (maxmind) to extensions modules (+ fraudlabs). This need to be updated too.

**Comment by villagedefrance** [comment]
MaxMind and FraudLabsPro have been updated.

**Comment by gob33** [comment]
Corrections on Maxmind:
https://github.com/opencart/opencart/pull/3231

**Comment by tiborbesze86** [comment]
Corrections with the new changes in the module folder structure:
https://github.com/opencart/opencart/pull/3239
