### ISSUE TITLE
Administration Theme Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#100]
Please note that I've noticed some Styling issues with the **Overclocked Administration Theme**.
As you can see, the dark-gray bars appear, breaking the styling.
This happens in a lot of admin sections (the screenshots just demonstrate a few).
**Tested on v1.10.2**

![theme](https://user-images.githubusercontent.com/3336728/34383581-c924b05a-eb1e-11e7-9aa6-02c141a3acab.png)
![theme2](https://user-images.githubusercontent.com/3336728/34383582-ceed0730-eb1e-11e7-8ae8-65e63b1302bb.png)
![2](https://user-images.githubusercontent.com/3336728/34412621-feb1bbf0-ebe6-11e7-8b16-0996fddd8e68.png)

**Comment by villagedefrance** [comment]
This is not a error. It is meant to be like that.
It is an alternative CSS "list" style called "highlight".
It is designed to put in perspective important or related entries.

**Comment by Tangol** [comment]
Got it.
It can be closed, thanks!
