### ISSUE TITLE
Core SEO URLs don't work

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#101]
While testing **v1.10.2.0 (OCE)** on Bitnami WAMP Stack-7.0.22-1, I've noticed that the **SEO URLs** don't work for core links.
`LoadModule rewrite_module modules/mod_rewrite.so` is enabled in Apache and also in the Server Settings.
![url](https://user-images.githubusercontent.com/3336728/34409893-5e9a3d7e-ebd5-11e7-938c-2d555c47d47f.png)

- The result is the same as with SEO URLs disabled.
![seourl](https://user-images.githubusercontent.com/3336728/34410023-08ddd71e-ebd6-11e7-9ce0-68e438069b9c.png)
![map](https://user-images.githubusercontent.com/3336728/34411448-5b56d7a8-ebdf-11e7-875b-2c0264fb9062.png)

**Comment by villagedefrance** [comment]
Not true.
Try using the "Seo Url Manager" tool and create a new Sitemap entry if it doesn't already exist.
Every page without **filter, sort** or **refine** can be rewritten.
