### ISSUE TITLE
VQMod Error

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#104]
Just installed a fresh **v1.11.0 Beta** on commit https://github.com/villagedefrance/OpenCart-Overclocked/commit/525e2b1f43ded7c26652bb1bbc27b6948b323675 and got the following error @VQMod:
![vq_error](https://user-images.githubusercontent.com/3336728/34959186-01360e52-fa3e-11e7-9ad6-222e2866e37f.png)

**Comment by villagedefrance** [comment]
You get an error saying:
Search Not Found: $this->data[text_voucher]
The [text_voucher] variable is definitely present in the Header Controller & Language files.
I'm not sure where your error comes from.

**Comment by Tangol** [comment]
It's a clean install, with all modules/mods enabled.
I will test some more, to see if it happens again.

**Comment by villagedefrance** [comment]
@Tangol : Are you still having trouble with vQmod?
I have updated vQmod code recently, mostly cosmetic. I had no errors whatsoever during testing.
Let me know if we can close this issue.

**Comment by villagedefrance** [comment]
Apologies for not having spotted the bug earlier.
