### ISSUE TITLE
Setting to enable/disable right click prevention

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#109]
I've noticed that by default, right clicking on the website is disabled https://github.com/villagedefrance/OpenCart-Overclocked/commit/9f9539797f81ea8c906f8410fb615f6d914841ed.
Not being able to disable this feature, may cause some usability issues, as users may want to open some products in different tabs, and not everyone knows about the scroll button click to open in a new tab. 

So my suggestion is an option to toggle this feature on and off.
Thanks!

**Comment by villagedefrance** [comment]
Done.
The selector is now part of the Default Theme settings so it will be dependent on template rather than main store settings.
Thank you for your suggestion.
