### ISSUE TITLE
Unmark All button issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#110]
Please note that the **Unmark All** button at **User Groups** doesn't work.
When you click on it, it doesn't do anything.
![unmark](https://user-images.githubusercontent.com/3336728/35781927-eacf4cf8-09f8-11e8-9659-f06acf71385c.jpg)

Edit: The same issue at **EU Taxes**
![taxes](https://user-images.githubusercontent.com/3336728/35781993-1b5a0024-09fa-11e8-9a03-cfe1cf70c2b5.png)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/a16e05a2b8fa436c056a673c7ae33f29eae460df

**Comment by villagedefrance** [comment]
Kudos for spotting this one!
I have found the problem ...
A commit will follow asap with the fix.
