### ISSUE TITLE
News Articles Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#114]
When you post a news article that has an **Article Image** attached, the text of the article goes right at the edge of the image, with no space between.
This looks kinda bad.

![news](https://user-images.githubusercontent.com/3336728/35939787-dcf69212-0c55-11e8-9fba-6a0a9a53d224.jpg)

Also, I've noticed that the default **Image Viewer** for news articles is **ColorBox**, which is a poor choice as it's not responsive.
I've found that **Magnific** works best. :)

PS: it would be nice if the Blog/News post could also show a preview of the text, like **[here](https://www.journal-theme.com/11/blog)**.

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/77335e5325ed04f07c8507987815affc43cb1ef1

**Comment by Tangol** [comment]
Please note that after the recent commits, the **Views Counter** doesn't update in the front end.

![news](https://user-images.githubusercontent.com/3336728/37306742-5549af6a-2641-11e8-9e90-94466f51bbdf.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/5c087969e2d400083c1d99ce2c576fab86910508

**Comment by villagedefrance** [comment]
Everything seems to be working fine now.
Closing this issue.

**Comment by Tangol** [comment]
Please note that the **Views Counter** still doesn't get updated in the front end.
It always shows 0.
