### ISSUE TITLE
New Permission at User Groups

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#116]
With OpenCart OverClocked being a multi-user system, it gives us the possibility to have multiple departments, like sales, support etc.
Some of these departments need to have very limited access, however the **Dashboard** shows pretty sensitive information like Total Sales, No of Orders etc.
The customer support guy doesn't need to see how much profit the store is making, if you know what I mean. 😀

So I'm thinking we need a **show/hide dashboard** option at **User Groups**.
If a user group doesn't have the permission to view the dashboard, at login, this page should appear.

![dash](https://user-images.githubusercontent.com/3336728/36002380-94827964-0d32-11e8-9777-501501363d12.jpg)

Thanks!

**Comment by Tangol** [comment]
I've just installed a fresh copy of OC Overclocked and when I logged in on the **admin** account, I got the **Permission Denied** message @Dashboard.
To get it to work, I had to go to **User Permissions** and select all then save.

So by default, at install, we should give the **Top Administrator** access to the Dashboard.
Commit https://github.com/villagedefrance/OpenCart-Overclocked/commit/b262b02c96b30eb0c3b066ffeaa715dcc10bcc10

Thanks!

**Comment by villagedefrance** [comment]
Yep, I am aware of that and I will update the permissions for fresh install later (before RC release).
... but the permission denied will always show on site upgrade.

**Comment by Tangol** [comment]
Works as it should.
Can be closed.

Thanks!
