### ISSUE TITLE
Logical reorder of the Admin Menu

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#117]
I've noticed that right now, the different **Admin Menu** settings are chaotically mixed together.

In my opinion the logical order of the Menu should be like this:
**Dashboard** - **Catalog** - **Sales** - **Reports** - **Tools** - **Extensions** - **System**

What do you think?

Thanks!

**Comment by villagedefrance** [comment]
Interesting, I never really thought of changing the default OC order but what you are saying makes sense. I tried to be critical of your new classification but I can't fault it. I think we need to do this. Thank you for another great suggestion!

**Comment by villagedefrance** [comment]
I have swapped "System" and "Extensions" tabs for better results on smaller screens since "Extensions" sub-menu doesn't extend to the right unlike the others, meaning no overflow. Some minor style tweaks are still needed for perfect results.
