### ISSUE TITLE
"highlighted" fields in the Admin

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#119]
A while back when I first tested OpenCart Overclocked, I was under the impression that there's a **[bug](https://github.com/villagedefrance/OpenCart-Overclocked/issues/100)** in the admin styling, having those fields grayed out.
It looks so bad...

So I thought about highlighting in a different way, and came up with this:
**line 1284**
```
table.form > tbody > tr.highlighted, table.form-slim > tbody > tr.highlighted {
    background: #30353A;
    -webkit-box-shadow: 0 0 4px #36AAD8; 
    -moz-box-shadow: 0 0 4px #36AAD8; 
    box-shadow: 0 0 5px #36AAD8;
}
```
![highlight](https://user-images.githubusercontent.com/3336728/36077053-67dc2700-0f6e-11e8-9115-7fbf8f734d5c.jpg)

What do you think?

**Comment by villagedefrance** [comment]
Not exactly like you suggested but I think it is satisfactory.

**Comment by Tangol** [comment]
Looks good.
Can be closed.

Thanks!
