### ISSUE TITLE
SEO Friendly Index URL

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#120]
At install, when you enable SEO firendly URL's, could you please add a rewrite for the site index too?
```
RewriteCond %{QUERY_STRING} ^route=common/home$
RewriteCond %{REQUEST_METHOD} !^POST$
RewriteRule ^index\.php$ http://%{HTTP_HOST}? [R=301,L]
```
This needs to dynamically adjust to the site path.
For example, if the site is located inside a folder, the cond should be:
`RewriteRule ^index\.php$ http://%{HTTP_HOST}/folder? [R=301,L]`

Could this be done, or it may cause issues with multi-store setups?

Thanks!

**Edit:** Found that for multi-store, the rewrite would look like this:
```
RewriteCond %{QUERY_STRING} ^route=common/home$
RewriteRule ^index\.php$ /? [R=301,L]
```

**Comment by villagedefrance** [comment]
Mmmh ... I'm not too sure what to do with this one.
As far as I can tell, the site path is already generated dynamically. I do most of my testing on Xampp and I hardly get any issues installing in multiple sub-levels of folders.
Also, it is very unlikely to have multi-store already setup at install, if not impossible.
And also my .htaccess is by far the most advanced compared to official OC, Pekku's v1.5.6.5 Edge, Community Edition or even Arastta.
I leave this open for now just in case something more specific needs doing.
