### ISSUE TITLE
Checkout issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#122]
I've created a new customer account, and tried to place a quick order.
At the checkout page I got the following:

- Inserted the address, set to deliver to that address and click continue.
![address](https://user-images.githubusercontent.com/3336728/36108807-5b894b1e-1026-11e8-83ba-6ac2554c9188.jpg)

- The result:
![result](https://user-images.githubusercontent.com/3336728/36108923-958bbbda-1026-11e8-8258-2e1aea560577.jpg)

**As you can see, the address doesn't get updated at the final checkout.**

_PS: I didn't previously setup a default address in the Address Book.
Just placed the order and inserted the address on the spot._

_PS2: It works as it should if before placing an order, you setup a default address in the Address Book._
![correct](https://user-images.githubusercontent.com/3336728/36109306-aadcd23e-1027-11e8-9118-4c40050bbd06.jpg)

Tested on commit https://github.com/villagedefrance/OpenCart-Overclocked/commit/0e3585384ba6858dc904092fb27a926ec6363b24

**Comment by villagedefrance** [comment]
Tested on Firefox with the same address as your example and no problem.
I can't test with MS Edge since i'm using win7 but I can't see why this would be the reason.
Please confirm your findings so if there is a bug we can pinpoint where it comes from and fix it.

**Comment by Tangol** [comment]
Hmm, I guess the issue appeared because the customer account was created by me in the **Admin** and I didn't provide an address.

When you register the account on the website, it doesn't let you continue if you don't provide an address.

**Comment by Tangol** [comment]
It works ok now.
Issue fixed, can be closed.

Thanks!
