### ISSUE TITLE
Download PDF Invoice for Customers

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#123]
One important thing (in some countries, stores are compelled by law to have it) is the customer's ability to download the pdf invoice of his order.
We have this ability in the **Admin**, but not in the **Order History**.
So we should have a button near the **View** invoice, for downloading it.
![pdf](https://user-images.githubusercontent.com/3336728/36118098-8bd2abd0-1044-11e8-9a05-c43d02b93bcf.jpg)

Thanks!

**Comment by gob33** [comment]
I OpenCart this is done by some extensions and not in the core.

**Comment by Tangol** [comment]
@gob33 I know there are extensions available for this feature, but given that Philippe bundled **DomPDF** with the core, and we already have it working in the Admin, why shouldn't it be present in the Customer Account also?

**Comment by gob33** [comment]
DomPDF is just a library that allows PDF files to be created on-the-fly.
Was added to OC with plans to use it for PDF Invoices, but can be used for anything else requiring nice output.
If you want PDF Invoices, why not adapt "PDF Invoice Pro" to Overclocked for exemple or any other extension dealing with PDF invoices (some are free) ?

**Comment by Tangol** [comment]
Please note that at the moment, clicking on the download button generates the entire order history, which is unnecessary.
The customer should be able to download, only the **INVOICE** (the same one as in the Admin).

Also the **title** attribute of the button should be `title="Download Invoice"`

![history](https://user-images.githubusercontent.com/3336728/36979072-07818bf2-208f-11e8-98bd-b74ef70963c3.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/eaf8a83b3a19f4110add704a303e8a7d444e6c5a

**Comment by Tangol** [comment]
Works perfectly now.

It can be closed.
Thanks!
