### ISSUE TITLE
.htaccess issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#129]
Regarding [this commit ](https://github.com/villagedefrance/OpenCart-Overclocked/commit/5d3a56de8167d199e2ffdafee0bfd3f8b2029d96#diff-ed27605b869e8df3e28a1efc7a8479df), the `.htaccess` file needs to be located inside the **admin** folder, alongside the `.htpasswd` file, having only the following code:
```
## To further protect your Admin login, use the ".htpasswd.txt" and the .htaccess file located in the Admin folder,
## Rename it ".htpasswd" / ".htaccess", then uncomment and configure (if necessary) the following settings:

# AuthType Basic
# AuthName "Restricted Area"
# AuthUserFile path_to_file/admin/.htpasswd
# Require valid-user
# ErrorDocument 401 "<H1>Error 401</H1> Access to this page is restricted. Please enter valid credentials."
```

If you enable the mod inside the main `.htaccess` file, you won't be able to access the website.
Ref https://github.com/villagedefrance/OpenCart-Overclocked/issues/125

Thanks!

**Comment by villagedefrance** [comment]
Ok got it. 
I will update.
