### ISSUE TITLE
[1.7.0.RC1] Dashboard resume

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#13]
For nice aligment in all langages, I suggest changing the dashboard resume
![1 7 0 rc1_dashboard](https://cloud.githubusercontent.com/assets/4837882/8736899/f353618c-2c1c-11e5-8ca1-9d2ead537d53.png)
to something like Arastta (but with icon at left, then 2 lines):
![arastta_dashboard](https://cloud.githubusercontent.com/assets/4837882/8736907/092c3074-2c1d-11e5-9616-3a037a1a43e3.png)

**Comment by gob33** [comment]
And at the bottom, the latest 10 could be extended like:
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=15031
to show more tabs.

**Comment by villagedefrance** [comment]
Dashboard updated ...
