### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#132]
Got this random error when clicking around the menu in the Admin.

`2018-02-18 11:36:33 - PHP Warning: unlink(C:/Bitnami/wampstack-7.0.22-1/apache2/htdocs/oce/system/cache/cache.seo_url_map.1.1518982591): No such file or directory in C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\oce\system\library\cache.php on line 16`

![randomerror](https://user-images.githubusercontent.com/3336728/36355985-1d60108e-14f4-11e8-8c69-9df3a6b79ca4.jpg)

Tested on: https://github.com/villagedefrance/OpenCart-Overclocked/commit/bafc49c0c84471d3000e7faebc9f853339179212 - Firefox 58.0.2

**Comment by villagedefrance** [comment]
Is this still happening or issue can be closed?

**Comment by Tangol** [comment]
Got this error only once, randomly. 
So I would keep this report open, as it seems that there's something fishy going on with the cache.
My suggestion is to wait and see if someone else gets it and maybe that would help us pinpoint the exact cause.

**Comment by Tangol** [comment]
I haven't gotten this error since then, so I think it's safe now to close it.

Thanks!
