### ISSUE TITLE
Prettify Texts

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#134]
In order to keep consistency and have a more professional look, some texts need to get updated.

![texts](https://user-images.githubusercontent.com/3336728/36394252-0e300b28-15bc-11e8-8bca-8afaf2623c90.jpg)

```
Html > HTML
Seo Url status > SEO URL status
Seo Url Manager > SEO URL Manager
Api Key Manager > API Key Manager
id > ID 
```
PS: the above texts need to get updated in the submenus also.

Thanks!

**Comment by Tangol** [comment]
Missed one more:
![url](https://user-images.githubusercontent.com/3336728/36500810-fa24f326-174d-11e8-9fad-21abef2dba04.jpg)

**Comment by villagedefrance** [comment]
Yes, well spotted. Thanks.
