### ISSUE TITLE
Products Stock Report Colors

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#136]
Please note that the **Products Stock Report** shows RED for both the low stock and out of stock products.

However, it should display ORANGE for the **low stock** products, and GREEN for normal stock, like in the **Orders** page.
This helps us differentiate between stock levels.

![stock](https://user-images.githubusercontent.com/3336728/36526835-55fd52e6-17b8-11e8-8f0a-873b481aaa41.jpg)

Thanks!

**Comment by villagedefrance** [comment]
Good point! Thanks for the heads-up.
