### ISSUE TITLE
PDF Invoices Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#137]
Please note that the downloadable **PDF** Invoices (Shipping Label, Pick List, Delivery Note, Invoice) do not show the website logo when downloaded.

![logoinv](https://user-images.githubusercontent.com/3336728/36551667-cf271844-1800-11e8-9e5d-a207b2564fa8.jpg)

The logo is shown only when you view the invoice in a new tab.

![viewlogo](https://user-images.githubusercontent.com/3336728/36551789-187333fc-1801-11e8-9256-1f620c8099a2.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/371bbb0da8ac3ddb9c0f43e089cb823bc5c9b465

**Comment by villagedefrance** [comment]
Yes, this is a known issue.
DomPDF simply doesn't convert images.
I tried many times but with no luck.

**Comment by Tangol** [comment]
Hmm, in it's changgelog is says that it supports image rendering.
I also found this: https://stackoverflow.com/questions/22779495/dompdf-image-not-found-on-live-server/22911050?noredirect=1#22911050
And this: https://stackoverflow.com/questions/15153139/dompdf-remote-image-is-not-displaying-in-pdf

Also, it seems that 2 pages are generated for every pdf.
One page with content and the other is empty.
This could become a issue when printing tons of invoices...

**Comment by villagedefrance** [comment]
Correct, two pages (including a blank one) are being generated.
I know that it should render images but like I said, I tried many times in the last 2 years without success. ... I even replaced the default "no image" file with a white background because it kept showing.
It is an issue, I agree, but I cannot fix it. Any PR on this will be considered.
Otherwise, headed paper will be the answer here.

**Comment by villagedefrance** [comment]
I think I have finally fixed this! :)
@ Tangol: Thanks for the links and pushing me to fix it.

**Comment by Tangol** [comment]
No, thank you Philippe!
You are a boss! 😁

**Comment by Tangol** [comment]
Works fine.
All issues are fixed.

Can be closed.
Thanks!
