### ISSUE TITLE
HTML Module Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#139]
I don't see the reason to use **CKEditor** when inserting HTML, as it doesn't parse code very well.
For example, if you want to add some Adsense code, it doesn't work.
```
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3066913885905030"
     data-ad-slot="3286095903"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

For the **HTML Module** we need [CodeMirror](https://codemirror.net/), that supports HTML, CSS and JavaScript.
Something like this:
![editor](https://user-images.githubusercontent.com/3336728/36644843-b95bf15a-1a68-11e8-915a-66edc11f601a.jpg)

Thanks!

**Comment by villagedefrance** [comment]
Ok, but CodeMirror is already in CKEditor (Source button, top left).

... and there is a contextual help message to explain this:
HTML Code:
Use "Source" to enter or paste a script. Enter any other content directly in the text editor.

This solution has been working great for over 3 years! Are you sure you want this updated?

**Comment by Tangol** [comment]
Just try to insert the code above, using the source option in CKEditor and see what happens.
It doesn't work.
Some portions of the code get removed...

**Comment by villagedefrance** [comment]
Ok, you are correct, there is a problem.
I will have a look.

**Comment by villagedefrance** [comment]
It turns out that CKEditor strips out all empty html tags.
In your example, <ins></ins> is empty and therefore is removed.

... but if you change it slightly by adding "." or "nbsp;", it will then stay:
`<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3066913885905030"
     data-ad-slot="3286095903"
     data-ad-format="auto">&nbsp;</ins>`

... I haven't found a proper answer for this just yet, but at least it explains what's happening.

**Comment by Tangol** [comment]
Yes, it works with `&nbsp;`

In this case I guess we just have to update the HTML description:
**HTML Code: Use "Source" to enter or paste a script (use `&nbsp;` for empty tags). Enter any other content directly in the text editor.**

**Comment by Tangol** [comment]
Please note that **CKEditor5** doesn't work for html.
Ref https://github.com/villagedefrance/OpenCart-Overclocked/commit/eb15cabd706a70368a1013ecfc0898ebcb55ebc3#commitcomment-27818985

Wouldn't be easier to add [CodeMirror](https://codemirror.net/)?
We don't need a full text editor for HTML.

**Comment by villagedefrance** [comment]
I spent half of the day on this :(
I had a look at CodeMirror. It is the best choice of course, but has so many internal dependencies (multiple JS and CSS) that I wonder if this is the right answer.
I've got to think about it ...
Thanks again for the feedback.

**Comment by Tangol** [comment]
The simple HTML textarea works perfectly.
I consider the issue solved.

Can be closed.
Thanks!

**Comment by villagedefrance** [comment]
I also think this is sufficient with a Textarea. It is just a module after all and if people want a more advanced solution then they can use another module. It does leave some room for developers to do better.
