### ISSUE TITLE
[1.7.0.RC2] Tabs making right shift

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#14]
Something leaving since a long time (same in OC): when many tabs present, so that a wrap is done at the right margin, the next content is shifted right to the last tab.
As im not a css expert, something to do with "floating" perhaps ?
Particulary in Products->Edit
![1 7 0 rc2_shift](https://cloud.githubusercontent.com/assets/4837882/8894163/ac66a8e6-33ac-11e5-8742-974214d2331a.png)

**Comment by IP-CAM** [comment]
there is a fix for that, look here:
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=19367
Ernie - IP-CAM

**Comment by gob33** [comment]
The fix seems to correct partialy: the last tab "Marketplace" do the yoyo when clicking.
Better but not perfect.

**Comment by villagedefrance** [comment]
Tabs have now been updated to fix the issue.
Thanks for the heads-up guys.
