### ISSUE TITLE
Cart version in site source code

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#142]
Please note that currently, the source code of the website shows the OpenCart Overclocked version. 
`<meta name="generator" content="1.11.0 Beta" />`

This is an issue, as a hacker would know what version to target when searching for vulnerabilities.
So it should be removed/hidden form the source code.

![version](https://user-images.githubusercontent.com/3336728/36760296-f15fe2bc-1c22-11e8-8074-a19a75f49e92.jpg)

Thanks!

**Comment by villagedefrance** [comment]
Removed as suggested.
