### ISSUE TITLE
New option for adding Reviews

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#146]
At the moment you can only Enable/Disable the reviews, and if enabled, anyone can post.
This is fine, but we also need another option, to limit the reviews entry based on the user status - **Logged In/Logged Out**.

So the user has to be **logged in** in order to post a review.
This adds another layer of authenticity to the reviews, as it limits entry, only to customers that have accounts on the website ("bye bye fake reviews").

![reviews](https://user-images.githubusercontent.com/3336728/36980127-1ac154d8-2092-11e8-8977-d5fffd0f6f72.png)

Thanks!

**Comment by villagedefrance** [comment]
Another great suggestion! ... it should be easy to implement.

**Comment by Tangol** [comment]
The feature works great.

Can be closed.
Thanks!
