### ISSUE TITLE
[1.7.0.RC2] Adding a filter by country on zones page

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#15]
Im tired of clicking on next page to find my zones.
Could we have a filter at top on the zone page for fast access ?
Like http://www.opencart.com/index.php?route=extension/extension/info&extension_id=7891
or http://www.opencart.com/index.php?route=extension/extension/info&extension_id=17456
Or better, a top filter bar on each column with autocompletion for zones, countries, and geo_zones.

**Comment by gob33** [comment]
And more, extending filter to categories, products, manufacturers,... exactly like OC or Arastta.

**Comment by villagedefrance** [comment]
Just finished the Admin Filters today, autocomplete style, for Zones, Countries, Categories, Manufacturers, Downloads and Reviews. Products already had filters.
