### ISSUE TITLE
Account Module

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#150]
I've noticed that the account module is active by default and has a layout set.
This is unnecessary (and visually out of place), as we already have **New Customer** (register) and **Returning Customer** (login), at the Login page.
It's kinda confusing having a 3rd login box (My Account) in there, so it should be disabled.

![account](https://user-images.githubusercontent.com/3336728/37220557-a4475708-23cf-11e8-8d83-a2331c4c8a2c.jpg)

Thanks!

**Comment by villagedefrance** [comment]
Updated as requested.
Closing issue.
