### ISSUE TITLE
Fixer.io API Deprecated

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#153]
Please note that https://github.com/fixerAPI/fixer got an update (see github description), and the old API is now deprecated.
The new API insn't free anymore, so I think we should find some other solution.

Found this: https://stackoverflow.com/a/8391430 and https://www.mycurrency.net/page/Free+Currency+Converter+API (based on Yahoo Finance?)

Thanks!

**Comment by villagedefrance** [comment]
Thanks for reporting this one.
I updated with Fixer not to long ago because Yahoo Finance stopped working last year. Now Fixer must be getting too many requests on their server amd decided to change their API.
I will see what other alternative we have.
A free service would be preferable of course.

**Comment by Tangol** [comment]
Is it normal that only the default currency gets updated daily?
Shouldn't all the available currencies get updated?

![currency](https://user-images.githubusercontent.com/3336728/37434936-034991a8-27ea-11e8-82d1-6ba19646edb0.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/55be94840f5855ab3cc804a31e18978c70ef110f

**Comment by villagedefrance** [comment]
I fixed the update script using FloatRates xml daily feed.
I also added the optional Alpha Vantage API (json) script as an alternative. A free API key is required for this one but the data accuracy could be superior. The API key needs to be entered in the Settings (and can be backed-up in the API key Manager).
I consider this issue closed.
