### ISSUE TITLE
YouTube Video

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#154]
In the **Data** tab of the **Product**, we have the ability to add YouTube videos.
The option says: `Enter one or more (comma separated) YouTube video codes. (optional)`

My question is, how can we add more than 1 video, as comma separation of codes, doesn't work.

Thanks!

**Comment by villagedefrance** [comment]
It used to work but it looks like it doesn't anymore.
I'm committing an update right-now.

**Comment by villagedefrance** [comment]
Now only supports one video.
Closing issue.
