### ISSUE TITLE
Error when viewing the Pick List

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#156]
Got the following error:
`2018-03-18 14:18:34 - PHP Notice: Array to string conversion in C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\oce\admin\view\template\sale\order_pick_list.tpl on line 94`

![err](https://user-images.githubusercontent.com/3336728/37571266-15b37a54-2b03-11e8-96d3-1103909ac699.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/aee2e52b359f2fc63c93fac5eac1976c20616bf0

**Comment by villagedefrance** [comment]
This should be fixed now.
Closing issue.
