### ISSUE TITLE
Prettify the Invoices (Part 2)

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#159]
Some little things left:

- The **Order Details**, **Invoice**, **Delivery Note** and **Pick List** (downloaded PDF's) details should be moved to the right, the same as the store details.
That part of the invoice should be divided in 2 equal boxes, like the Payment Address and Shipping Address.

![move](https://user-images.githubusercontent.com/3336728/37571410-e3e25c46-2b04-11e8-9d45-039a38786611.jpg)

- Missing icons for **Company Registration** and **Company Tax ID**.
Also, those two pieces of information should be moved just above the phone number and below the store address.

![icons](https://user-images.githubusercontent.com/3336728/37572031-dc9193a4-2b0d-11e8-8857-de3e2d758f67.jpg)

- The **Personal Data** pdf needs the same updates (with the little icons and stuff).

![data](https://user-images.githubusercontent.com/3336728/37572073-696938ae-2b0e-11e8-953c-30eab7b16f01.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/aee2e52b359f2fc63c93fac5eac1976c20616bf0

**Comment by villagedefrance** [comment]
I think I have covered all your points.
Store name also fixed (see issue #160).
I will add Bank details next.

**Comment by Tangol** [comment]
Ref https://github.com/villagedefrance/OpenCart-Overclocked/commit/42ceb2b72a51aa40b40382fac0fadca101bdeca1#commitcomment-28193719
This needs tweaking.

Thanks!

**Comment by Tangol** [comment]
Now it's perfect.
Thanks a lot Philippe!

Can be closed.
