### ISSUE TITLE
[1.7.0.RC2] Checkbox for demo products

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#16]
Something very useful would be to have a checkbox at install for not installing demo products (like in Zencart or Alegrocart) so that one can start a new empty site.

**Comment by villagedefrance** [comment]
Good idea. I will look into it ...

**Comment by gob33** [comment]
For me, its evident and ask why it has not been done before in OC.
I just came to see another merchant with demo and its products mixed.

**Comment by IP-CAM** [comment]
basically, such already exists:
http://www.opencart.com/index.php?route=extension/extension&filter_search=delete%20demo%20data

Ernie

**Comment by villagedefrance** [comment]
Done. Option added to load a clean SQL file at install. The new clean SQL file is now used for upgrading as well.
