### ISSUE TITLE
Pick List Issue

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#162]
Please note that viewing or downloading the **Pick List**, doesn't show show the status (**Picked** - YES/NO) or the **Backorder Reason**.

![pick](https://user-images.githubusercontent.com/3336728/37705867-0be05c40-2d06-11e8-87b1-8d348f0d2e55.jpg)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/ee278ec9075d8b3c8491f409e5b04f874d2725ef

**Comment by villagedefrance** [comment]
Not a bug!
The pick list is a warehouse document and not a customer document. It has to be blank for picking. The warehouse operator should fill the printed document by hand, then update the system depending on the outcome.
