### ISSUE TITLE
List/Grid Setting

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#166]
Please note that the **List**/**Grid** setting gets reset with every page refresh.

So if a users sets the searches to appear as a **Grid** and then he reloads the page, the setting gets reset and they show up as a **List** again.

![grid](https://user-images.githubusercontent.com/3336728/37879286-44a0dec0-307f-11e8-9330-1795df1bc517.jpg)

**Comment by villagedefrance** [comment]
Correct. That's not a bug.
The reason is simple: the script is "live" and doesn't use any cache so it can't remember last position (unlike the News collapsible panels and Product "Tabs").
As far as I now there is no solution to that minor problem.

**Comment by Tangol** [comment]
[Here's](https://github.com/opencart/opencart/commit/3c98816bac3bce776deec1c5ef6d8f68bb1b720d) how OpenCart fixed it.

**Comment by villagedefrance** [comment]
Nice! I am going to update this.
Thanks!

**Comment by Tangol** [comment]
Works fine now.
Can be closed.

Thanks!
