### ISSUE TITLE
News Preview

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#168]
Please note that the **News System**, should show a preview of the article, like it did in **v1.10.2 (OCE)**.
It just looked better and was more professional.

![news](https://user-images.githubusercontent.com/3336728/37980656-46e05776-31f4-11e8-8033-df5f2622a36d.jpg)

Thanks!

**Comment by villagedefrance** [comment]
My version does have a text preview.
Make sure you select the number of characters to show in Settings > Preference > News.

**Comment by Tangol** [comment]
After doing several tests, in order to prevent unexpected behavior like the one below, the **default** `Headlines News Character Limit:` should be set to `1200`.
**1200** looks best in all circumstances (different post types).

![headline](https://user-images.githubusercontent.com/3336728/37993098-3a4426b0-3216-11e8-9961-f938eb524e8d.jpg)

**Comment by Tangol** [comment]
Issue is fixed.
The report can be closed.

Thanks!
