### ISSUE TITLE
.htaccess Security Hardening

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#179]
Please note that currently, the error pages will display the Apache server version, along with the Operating System name of the host server. It also shows information about the Apache modules installed on the server.
This is bad practice, as we shouldn't offer any information about the web host, to potential hackers.

To fix this, we need to add the following to the `.htaccess`:

```
#Reduce Server HTTP Header to the minimum product (Apache) rather than showing detailed version information of the server and operating system:
ServerTokens Prod

#Remove the footer from error pages, which details the version numbers:
ServerSignature Off

# Hide X-Powered-By and Server headers, sent by downstream application servers:
# Note you need both below as the "always" one doesn't work with Jboss for some reason.
Header always unset "X-Powered-By"
Header unset "X-Powered-By"
```

Also, Apache allows us to add XSS protection with the following command:
```
<IfModule mod_headers.c> 
# Set XSS Protection header
Header set X-XSS-Protection "1; mode=block" 
</IfModule>
```
This is especially useful for users of older browsers that don't support the **Content Security Policy**.

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/1f76511907854d5875cca62fe03b29a2cf5a92a2

**Comment by villagedefrance** [comment]
Please note that I had to comment the first line "ServerTokens Prod" because the pages couldn't load. 
All other definitions seem to be fine.
Tested on local and live servers.
Thank you for another great suggestion!

**Comment by Tangol** [comment]
Issue fixed.
Can be closed.

Thanks!
