### ISSUE TITLE
Frontend Search Returns No results v.1.11.0 - Fix

### ISSUE THREAD

**Issue by Sp1kee** [villagedefrance/OpenCart-Overclocked#184]
Search returns No Results at "index.php?route=product/search" (frontend).
To fix the issue open "catalog\view\theme\default\template\product\search.tpl" in an editor. In lines 161 and 170 change the ".attr('value')" to ".prop('value')" (omit the quotes)

The changes in detail are:
Line 161: 
var search = $('#content input[name=\'search\']').attr('value');
Change to:
var search = $('#content input[name=\'search\']').prop('value');
Line 170:
var category_id = $('#content select[name=\'category_id\']').attr('value');
Change to:
var category_id = $('#content select[name=\'category_id\']').prop('value');

**Comment by villagedefrance** [comment]
Catalog Search code has been updated and should be working fine now.
Thank you.
