### ISSUE TITLE
Admin Search Filter Categories returns no results - Fix

### ISSUE THREAD

**Issue by Sp1kee** [villagedefrance/OpenCart-Overclocked#185]
The search filter at Categories in administration section is not working - always returns "No Results" (ver. 1.11.0). The solution for this is:
Open the file "admin\view\template\catalog\category_list.tpl" in an editor. Find the javascript function "filter()" - it must be at line 105. 
At line 108 replace the input variable ".attr('value')" to ".val()". This one is solving the issue.

Original line:
var filter_name = $('input[name=\'filter_name\']').attr('value');
Changes to:
var filter_name = $('input[name=\'filter_name\']').val();

**Comment by villagedefrance** [comment]
The last commit (currently) should have fixed this.
