### ISSUE TITLE
SwipeBox lightbox has stopped working.

### ISSUE THREAD

**Issue by villagedefrance** [villagedefrance/OpenCart-Overclocked#187]
SwipeBox doesn't work as expected anymore. A fix is unlikely, so chances are a replacement will be needed. Any suggestions?

**Comment by Tangol** [comment]
Found 2 options that seem nice:
1. [Lightcase.js](https://github.com/cbopp-art/lightcase)
2. [PhotoSwipe](https://github.com/dimsemenov/PhotoSwipe)

I would pick the one that's lighter on resources.

**Comment by villagedefrance** [comment]
Thanks Tangol,

I had a look at both the options you suggested, both good, but I ended-up with another one which looks more similar in style to SwipeBox. It's called "[GLightbox](https://github.com/mcstudios/glightbox)". The code seems to be well maintained and very well written too, so I went for it.

I have done the implementation on local and all looks good. I will be committing the update very shortly. Still need testing Touch/Swipe on mobile properly later.

**Comment by Tangol** [comment]
Please note that SwipeBox still appears as an option in the **News Module**, so it needs to get updated here also.

![swipe](https://user-images.githubusercontent.com/3336728/41821829-1d092e8c-77ef-11e8-9118-10795b377aab.png)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/af061b111c8977478be878cb4ec1729b8e47a288

**Comment by Tangol** [comment]
Viewbox seems to be working nice.
The issue can be closed.

Thanks!
