### ISSUE TITLE
[1.7.0] Missing payment modes

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#19]
Comparing with OC2.0.3.1, few payment methods are absent (or OC added some between).
Need some rework in that directory.

**Comment by villagedefrance** [comment]
Yes, OC added some in v2.0.+.
I already added Global Payment a while ago and will implement the others in time.

**Comment by gob33** [comment]
Globalpay has changed too.

**Comment by gob33** [comment]
And I think it is better in translation to separate title text from help like in 2.x
Just add the <br /> in the .tpl
It is easier to port translations from 2.x and a different css can be applied to help and text.
