### ISSUE TITLE
[1.7.0] languages in design/footer

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#20]
Here i dont understand why twice language tabs ?
![snap4](https://cloud.githubusercontent.com/assets/4837882/9471224/a04457c4-4b4f-11e5-9a90-283dc9a21070.png)

**Comment by villagedefrance** [comment]
The Top one is for the "Block name" ("Browse", in your screenshot).
The inline ones are for each "Link name" in that Block.

**Comment by gob33** [comment]
I understand but found that page incoherent.

**Comment by villagedefrance** [comment]
Well, this is the way I've done it. It works fine as far as I can tell.
I am always open to suggestions and better ways of presenting things, so feel free to share if you know a better way. I'm happy to merge pull-requests.
