### ISSUE TITLE
[1.7.0] Category name not displayed in product detail form

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#21]
In tab "Links" of product details, the category box has incorrect display.
OPENCART-OCE-1.7.0\upload\admin\controller\catalog\product.php
Line 1146 should be with parenthesis:
	'name'  => ($category_info['path'] ? $category_info['path'] . ' &gt; ' : '') . $category_info['name']

**Comment by villagedefrance** [comment]
Thanks. I've just corrected it.
