### ISSUE TITLE
[1.7.0] About sort order in columns.

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#25]
Often in the header of .tpl files, for sorting you write something like:
```
<td class="left"><?php if ($sort == 'cd1.name') { ?>
  <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
  <?php } else { ?>
  <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?>&nbsp;&nbsp;<img src="view/image/asc.png" alt="" /></a>
<?php } ?></td>
```
But the asc.png is useless here as it is done by the class="asc" or class="desc".
Like in the Windows Explorer, there is only one column which shows the current sort in use with the triangle. No need to display triangles on the other columns which is confusing.
Good code is:
```
<td class="left"><?php if ($sort == 'cd1.name') { ?>
  <a href="<?php echo $sort_name; ?>" class="<?php echo strtolower($order); ?>"><?php echo $column_name; ?></a>
  <?php } else { ?>
  <a href="<?php echo $sort_name; ?>"><?php echo $column_name; ?></a>
<?php } ?></td>
```

**Comment by villagedefrance** [comment]
I agree that it could be a bit confusing but at the same time it is very useful, because the down arrow shows that the column is sortable, which is not the case for every column, and this why I added the asc.png to all the sortable columns.

I am open to suggestions to make this better and less confusing.

**Comment by gob33** [comment]
So a double arrow greyed or black would do the trick.
![sortable-columns](https://cloud.githubusercontent.com/assets/4837882/9663276/ec82af26-5263-11e5-94b5-6d785cbeaa9c.png)

**Comment by villagedefrance** [comment]
Good suggestion. I am going to try to implement the double arrows in the next few days.
I also like the action buttons on the left in your screenshot :)

**Comment by villagedefrance** [comment]
Done!
Again, thank you for all your ideas. I am very grateful for helping me thinking "outside the box".
