### ISSUE TITLE
[1.7.1] Group name

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#29]
In system/library/user.php, it had ben added the group ID of the current user.
So why not set the group name at the same time with a function like getGroupName() ?

**Comment by villagedefrance** [comment]
Good point. I will have a look ...

**Comment by villagedefrance** [comment]
Alright, I had a look today ...

I can see the practicality of having a getGroupName() function in system/library/user.php, but I don't think it is being used enough to justify its addition to the user class.

However, there is a function in the admin user model file to get the User Group Name.
It requires 2 parameters: $user_id and $user_group_id.
It can be called anywhere under admin provided the model file is loaded: 
$group_name = $this->model_user_user->getUserGroup($user_id, $user_group_id);

So I will not add it to the user class at this stage.

**Comment by gob33** [comment]
I have the case in one of my OC extension where i needed current user group id and group name.
In your 1.7, group ID is already set at login. Having group name in the same query is easy.
This prevent doing +1 query.

**Comment by gob33** [comment]
All you have to do is change
'''
SELECT permission
'''
to
'''
SELECT name, permission
'''
and add a function getGroupName() 
in library/user.php

**Comment by villagedefrance** [comment]
Yes, I actually tried that, but all I had as a result was a Url.
I'm not exactly sure why.
I will try to implement this again in time.
