### ISSUE TITLE
[1.7.2] Return key on login

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#32]
At login panel, it has been forgotten the form.submit() on return keypress in the view.

**Comment by villagedefrance** [comment]
This should be fixed now.
See commit: "Logins update due to weird IE bug"

**Comment by gob33** [comment]
Didnt understand what
```
<script type="text/javascript"><!--
$('#login input').keydown(function(e) {
	if (e.keyCode == 13) { $('#login').submit(); }
});
//--></script>
```
has to do with PCI compliance and MacAffee ?

**Comment by villagedefrance** [comment]
Nothing to do with PCI compliance and MacAffee, just a better code overall.
More importantly the '#login input' had no real meaning since there is no id "login" anywhere in the form to reference the script. The script was redundant.
