### ISSUE TITLE
[1.7.2] Manufacturer names

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#34]
Due to the splitting of manufacturer name in a new table 'manufacturer_description', the manufacturer list do not display any manufacturer if admin is in another language than english. In french, i get no results but in english i got the 6 demo manufacturers. At least, the english names should be displayed by default in list entries if no correspondance exists in the foreign language.

**Comment by villagedefrance** [comment]
Thanks again, I missed that one too.
Manufacturer Description was added in 1.7.2, but i didn't update the language model accordingly. Thats why it failed when you installed your language. Fixed now.

**Comment by gob33** [comment]
You must also add the corresponding line for 'manufacturer_description' in deleteLangage()
