### ISSUE TITLE
[1.7.2] About "Location" module

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#36]
In Admin, on the module page, there is a "Location" module.
I dont see where its settings are used and the utility of this module ???
I introduced some lines and checked Front pages but nothing visible...
Do not confuse with localization / location.
No trace in old OC versions. What is it for ??

**Comment by villagedefrance** [comment]
The module works with System > Localisation > Locations, which allows you to setup multiple store addresses (real brick & mortar stores).
The Store locations created can be displayed in each Product page, if you want to advertise that the product is available at these locations.
The module is to present to the customers all the different Store locations available.
Not the most useful module for most of us only selling virtually online, but it makes the Opencart multi-store concept a bit more complete.

**Comment by gob33** [comment]
Ok, i tested, it works in conjunction. Not evident at first.
