### ISSUE TITLE
[1.7.2] About revision numbering

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#39]
Would not it be better to have:
define('REVISION', '20151214');
or
define('RELEASE_DATE', '20151214');
without separation so that we can make a test directly like "if (revision < YYYYMMMDDD) then ..."
and adapt extensions code to your changes betweeen versions ?

**Comment by villagedefrance** [comment]
I'm ok with that.
The new revision numbering will be added in v1.7.4.

**Comment by gob33** [comment]
Yeah or you can add a third define with an integer (not a string) for direct comparison:
define('RELEASE_DATE', 20151214);

**Comment by gob33** [comment]
INTEGER please !!
define('REVISION', 20160108);

**Comment by villagedefrance** [comment]
Just added, but the change will only start from the next version.
