### ISSUE TITLE
[1.7.4] Where an affiliate connect ?

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#41]
Opencart has an "extra" entry in the front store footer where affiliates connect.
Here, can't find where affiliates could connect ???

**Comment by villagedefrance** [comment]
First, check in "Settings" that Affiliate Accounts are Enabled.
Then check that the Affiliate Account links are showing in the Site Map (they will be).
Because the Footer in OCE is Custom, you will have to add manually the link to the Affiliate Login if you need it.

**Comment by gob33** [comment]
Precisely, a merchant dont know he must add the link by hand in the footer.

**Comment by gob33** [comment]
Solved by Affiliate module in 1.8.0
