### ISSUE TITLE
Error in SQL catalog/model/account/recurring.php

### ISSUE THREAD

**Issue by botonakis** [villagedefrance/OpenCart-Overclocked#43]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'or LEFT JOIN `oc_order` o ON (or.order_id = o.order_id) WHERE o.customer_id = '0' at line 1
Error No: 1064

**The error can be fixed by changing line 92 from: **

		$query = $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "order_recurring or LEFT JOIN `" . DB_PREFIX . "order` o ON (or.order_id = o.order_id) WHERE o.customer_id = '" . (int)$this->customer->getId() . "'");

**to **

		$query = $this->db->query("SELECT COUNT(*) AS total FROM " . DB_PREFIX . "order_recurring orc LEFT JOIN `" . DB_PREFIX . "order` o ON (orc.order_id = o.order_id) WHERE o.customer_id = '" . (int)$this->customer->getId() . "'");

**Comment by villagedefrance** [comment]
Thanks Botonakis,
I have already updated the file using back-ticks (`or`) but I like your solution better, so I might changed it again. A patch is available at villagedefrance.net.

**Comment by villagedefrance** [comment]
Fixed in v1.7.6
