### ISSUE TITLE
Fatal Error on installation from master

### ISSUE THREAD

**Issue by skyosev** [villagedefrance/OpenCart-Overclocked#56]
This exception is being raised on install. Sorry, I don't have time to debug right now, so just filing the issue here.

Exception: Error: Key column 'supplier_address_id' doesn't exist in table<br />Error No: 1072<br />CREATE TABLE `oc_supplier_address` ( `address_id` int(11) NOT NULL AUTO_INCREMENT, `supplier_id` int(11) NOT NULL, `company` varchar(32) NOT NULL, `address_1` varchar(128) NOT NULL, `address_2` varchar(128) NOT NULL, `city` varchar(128) NOT NULL, `postcode` varchar(10) NOT NULL, `country_id` int(11) NOT NULL DEFAULT '0', `zone_id` int(11) NOT NULL DEFAULT '0', PRIMARY KEY (`supplier_address_id`), KEY `supplier_id` (`supplier_id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci; in /var/www/projects/test/_test/OpenCart-Overclocked/system/database/mysqli.php on line 39

### Call Stack

1	0.0008	273312	{main}( )	.../index.php:0
2	0.0288	3163368	Front->dispatch( )	.../index.php:92
3	0.0288	3163608	Front->execute( )	.../front.php:28
4	0.0297	3300368	call_user_func_array:{/var/www/projects/test/_test/OpenCart-Overclocked/system/engine/front.php:41} ( )	.../front.php:41
5	0.0297	3305312	ControllerStep3->index( )	.../front.php:41
6	0.0318	3347904	ModelInstall->database( )	.../step_3.php:9
7	4.1250	5319008	DB->query( )	.../install.php:37
8	4.1250	5319144	DBMySQLi->query( )	.../db.php:20

**Comment by villagedefrance** [comment]
No problem, I take care of it.
Thanks for the heads-up.
