### ISSUE TITLE
Cannot access sale/supplier module after installation

### ISSUE THREAD

**Issue by skyosev** [villagedefrance/OpenCart-Overclocked#58]
It seems there are no default permissions for the new supplier module. 
I noticed the same for 'payment/bluepay_hosted' too.

Regards.

**Comment by villagedefrance** [comment]
Default "supplier_group" does not insert in DB when Updating (yet), but should do on a clean Install. This is required in Settings (and Stores) so needs to be setup first if missing.
Dunno about Bluepay at this time ... I will check ...

**Comment by villagedefrance** [comment]
Permissions should be ok now.
