### ISSUE TITLE
[1.6.5.0] USPS rates

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#7]
USPS shipping rates need to be aligned with OC2.0
Priority Mail Express => Express Mail

**Comment by gob33** [comment]
Also same for Royal Mail, need to be aligned on OC2.0 as all has changed.

**Comment by villagedefrance** [comment]
Agreed! I will update them some time soon.

**Comment by villagedefrance** [comment]
USPS and Royal Mail Shipping have now been updated.
