### ISSUE TITLE
About coding standarts

### ISSUE THREAD

**Issue by skyosev** [villagedefrance/OpenCart-Overclocked#75]
I noticed that many changes to the coding standards are being currently committed. Wouldn't be good if OC Overclocked adheres to the official [PHP coding standarts](http://www.php-fig.org/psr/psr-2/) ? IMHO the most important one is omitting the closing ?> tag of the PHP files. There is also [good explanation on stackoverflow](http://stackoverflow.com/a/4499749) about the benefits. This is accepted in OC2 too.

**Comment by villagedefrance** [comment]
Yes, I have been testing the php code with SensioLabsInsight and had to make many changes.
Regarding the closing ?> on PHP files, you are right, I think it is time to remove them ...
