### ISSUE TITLE
[1.8.0] Unable to create new customer account in local

### ISSUE THREAD

**Issue by gob33** [villagedefrance/OpenCart-Overclocked#77]
The customer email new MX check makes validation in error because there is no connection in local so PHP checkdnsrr() fails. Check is too complicated.

**Comment by villagedefrance** [comment]
Strange ... all works fine on my Xampp local server.
Are you getting an error message in your log?
FYI: I added the MX check to "PP_Standard" and "Skrill" under Admin, you can test it there too.
Like I said, I have no issues with the Email check on my side. Please provide more details on the error if you can.

**Comment by gob33** [comment]
Im am on Wamp + PHP 5.4.3.
How can you check dns without an internet connection !!???

And this article http://www.devshed.com/c/a/php/email-address-verification-with-php
says checkdnsrr() function is not implemented on Windows platforms before PHP 5.3.0.

**Comment by villagedefrance** [comment]
Interesting ...
Do you think I should add a switch in Settings to turn it on/off ?

**Comment by gob33** [comment]
I was also thinking about checking connection but didnt know how do it.

**Comment by villagedefrance** [comment]
Does that fixes the issue and are you now able to add customers on local?

**Comment by gob33** [comment]
Ok it works.
I just would have renamed checkConnection() to isLocal.....() as
$connected = $this->checkConnection();
assume you are connected which is not necessary true at this point, the function tests only localhost.

If you could re-put the small code for RETURN KEY on Admin panel at login, would be good.

**Comment by gob33** [comment]
checkConnection() is an important function that can be used everywhere (payment connections).
You must move it to the system folder (library) and rename it to (e.g) "isLocalHost()"
