### ISSUE TITLE
Database cache inconsistency object/array

### ISSUE THREAD

**Issue by howdu** [villagedefrance/OpenCart-Overclocked#91]
Database query returns object but when fetched from cache it returns array. 

Throws error: Trying to get property of non-object when loading from cache.

E.g simple test

```php
$query = "SELECT * FROM " . DB_PREFIX . "product LIMIT 10";
$queryName = md5($query);
$result = $this->cache->get($queryName);
if(!$result){
	$result = $this->db->query($query);
	$this->cache->set($queryName, $result);
}

var_dump($result);
exit;
```

First run will return object:
> object(stdClass)[513]
>   public 'num_rows' => int 10
>   public 'row' => 

Second load from cache :

> array (size=3)
>   'num_rows' => int 10
>   'row' => 

It's caused from json_decode 2nd param being true in library/cache.php

> assoc
> When TRUE, returned objects will be converted into associative arrays.

http://php.net/manual/en/function.json-decode.php

**Comment by villagedefrance** [comment]
Ok, but why changing the current code?
All the cache requests are expecting arrays in return, so why do we need direct cache queries for?
