### ISSUE TITLE
Journal Theme Support

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#93]
Does OpenCart-Overclocked support the [Journal Theme](https://themeforest.net/item/journal-advanced-opencart-theme/4260361), as the theme developer states it's compatible with OpenCart 1.5.x ?

**Comment by IP-CAM** [comment]
OC Overclocked is no longer compatible to OC v.1.5.x in many ways, 
and a Journal Theme would have to be re-coded in several places, to 
make it work with later OC Overclocked Versions.
Ernie

**Comment by Tangol** [comment]
That's what I thought.
Thanks for the confirmation.
