### ISSUE TITLE
Missing title attribute for icons

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#94]
Missing `title=" "` attributes on mouseover for **Mail Log**, **Quote Log**, **Error Log** and **Seo Url Manager** icons.
![icons](https://user-images.githubusercontent.com/3336728/33852984-04c8b4fa-dec5-11e7-94dc-7e4589b5c791.png)

The same applies for **Add to Wish List** and **View Item** icons.
![icon](https://user-images.githubusercontent.com/3336728/33853961-937ea760-dec8-11e7-805b-c52504be59fd.png)

And many others in the Admin section.
![img](https://user-images.githubusercontent.com/3336728/34413583-02bc3a44-ebed-11e7-863b-c7dad3026b40.png)

It's not very user friendly, as you don't know what those icons do, before clicking them.
**v1.10.2**

**Comment by villagedefrance** [comment]
I generally agree with your remark.
However, I am also aware of the implications of title tags for touch screen devices. This is why I didn't put title tags on these links/images. It also simplifies the translation in other languages. I think the answer to this is more about finding better icons with a universal meaning (like the On/Off button on electrical goods for example). I am open to suggestions.

**Comment by Tangol** [comment]
The `title` attribute on icons, is very important in the **Admin** section (which isn't responsive anyway), as it prevents random clicking and frustration.
This issue caught my attention when I got into OpenCart Overclocked, as I was getting frustrated not knowing what the buttons did.

Also, we need to keep in mind that the platform is used by developers in creating websites for customers.
These customers will have a hard time discovering all the features, as the icons don't have descriptions...
