### ISSUE TITLE
Errors when trying to view the Cart

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#95]
Please note that on a fresh install (all modules active) I got this random error when trying to view the Cart.
![err2](https://user-images.githubusercontent.com/3336728/33853808-fd7e57a6-dec7-11e7-83ad-0b7399516a02.png)
![err](https://user-images.githubusercontent.com/3336728/33853666-6712ebce-dec7-11e7-8d62-ff3efa20611c.png)

`2017-12-11 12:57:25 - PHP Warning: Division by zero in C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\cart\catalog\controller\checkout\cart.php on line 136`

`2017-12-11 12:57:48 - PHP Warning: Division by zero in C:\Bitnami\wampstack-7.0.22-1\apache2\htdocs\cart\catalog\controller\checkout\checkout_one_page.php on line 216`

**Testing on v1.10.2**

**Comment by villagedefrance** [comment]
Not really an error but I added a fail-safe nonetheless.
A new Reward Points Rate entry has been added to the store Settings and needs to be filled, as the reward points are now currency based.
