### ISSUE TITLE
Code Optimisation

### ISSUE THREAD

**Issue by Tangol** [villagedefrance/OpenCart-Overclocked#97]
While performing some tests on the [Demo](http://demo.villagedefrance.net/index.php) page I've found the following:
- https://validator.w3.org/nu/?doc=http%3A%2F%2Fdemo.villagedefrance.net%2Findex.php
- https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdemo.villagedefrance.net%2Findex.php
- https://gtmetrix.com/reports/demo.villagedefrance.net/ckYUu4CZ

As you can see, some more tweaks and optimisations are needed.
Cheers!

**Comment by IP-CAM** [comment]
Well, it's a free Software, you're talking about, so better don't expect
a tuned Race Horse. But it can be tuned relatively easy, if one follows
the advises from GTMetrix & Co. 
Ernie

**Comment by Tangol** [comment]
@IP-CAM I know it's free software, but taking into consideration @villagedefrance desire to make it **faster, richer, leaner and even more user friendly** (hence the name Overclocked), I think it's important to point out every little issue, so it can be fixed/tuned to perfection :)
That's why I've also suggested this https://github.com/villagedefrance/OpenCart-Overclocked/issues/98

Cheers!

**Comment by villagedefrance** [comment]
Achieving 100% optimization is extremely hard (as @IP-CAM can confirm being quite good at it).
I do try my best to produce a clean validated code but some parameters are at server level, which I can't control. Also, I would like to point out that OCE is almost fully self-contained and has hardly any remote CDN dependencies. This makes OCE strong and reliable in my opinion but that means slightly longer page loading times. I have done a lot of work on caching to compensate for this.
Anyhow, if you have any suggestions or performance tips, feel free to share them.

**Comment by villagedefrance** [comment]
I'm looking forward for your results.

**Comment by Tangol** [comment]
I've noticed that **OpenCart-Overclocked** loads all the resources at the top of the page.
Best practices say that only `css` and and mandatory (to render the page) `js` should be loaded in the `<head>`.
All other resources should be loaded at the bottom of the page, before `</body>`.

[Best practices 1](https://developer.yahoo.com/performance/rules.html#js_bottom)
[Best practices 2 (on Rails but it also works for html/php)](https://rails-bestpractices.com/posts/2010/08/30/put-scripts-at-the-bottom/)

![scripts](https://user-images.githubusercontent.com/3336728/37310790-c5a05c58-264d-11e8-9ab4-527092a76166.jpg)

**Comment by Tangol** [comment]
Please note that I've noticed an error when inspecting the `index` page.

![err](https://user-images.githubusercontent.com/3336728/39517804-a3e79782-4e09-11e8-9144-39bd90a73b8c.png)

The error also appears when inspecting the admin page.

![err2](https://user-images.githubusercontent.com/3336728/39518021-46742736-4e0a-11e8-9d39-0815d970a278.png)


Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/cd4ab80837a02e8415746acc96bf8a5c38653b4d

**Comment by Tangol** [comment]
Found another one:

![err3](https://user-images.githubusercontent.com/3336728/39569277-658506e0-4ecd-11e8-9997-8654aef50ac9.png)

Tested on https://github.com/villagedefrance/OpenCart-Overclocked/commit/52541900b5731e5390e30e218b5277004266353b

**Comment by Tangol** [comment]
![pagespeed](https://user-images.githubusercontent.com/3336728/41609987-afbe9658-73f4-11e8-9d12-9a01eb85114e.png)

I just did another test on v1.11.0 and the performance increase is amazing!

I consider this task/report fulfilled.
Can be closed. 

Thanks a lot Philippe!
